blog/urls.py
from __future__ import annotations

from django.urls import path

from .views import all_posts_view, pdf_post_view, post_detail_view, post_list_view

urlpatterns = [
    path("", post_list_view, name="blog_postlist"),
    path("all/", all_posts_view, name="blog_allposts"),
    path("<str:level>/<slug:slug>/", post_detail_view, name="blog_postdetail"),
    path("<str:level>/<slug:slug>/pdf/", pdf_post_view, name="blog_postpdf"),
]

config/urls.py
from __future__ import annotations

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic.base import TemplateView

from quiz.models import Quiz

info_dict = {
    "queryset": Quiz.objects.all(),
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path(
        "sitemap.xml",
        sitemap,
        {
            "sitemaps": {
                "quiz": GenericSitemap(
                    info_dict,
                    priority=0.9,
                )
            }
        },
        name="django.contrib.sitemaps.views.sitemap",
    ),
    # third-party apps
    path("captcha/", include("captcha.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("newsfeed/", include("newsfeed.urls", namespace="newsfeed")),
    # own apps
    path("social-media/", include("socialmedia.urls")),
    path("blog/", include("blog.urls")),
    path("quiz/", include("quiz.urls")),
    path("", include("pages.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

markdownx/urls.py
"""
**MarkdownX** default URLs, to be added to URLs in the main project.

See URLs in :doc:`../../example` to learn more.
"""
from __future__ import annotations

from django.urls import re_path

from .views import ImageUploadView, MarkdownifyView

urlpatterns = [
    re_path("upload/", ImageUploadView.as_view(), name="markdownx_upload"),
    re_path("markdownify/", MarkdownifyView.as_view(), name="markdownx_markdownify"),
]

quiz/urls.py
from __future__ import annotations

from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from quiz.models import Question

from . import views

info_dict = {
    "queryset": Question.objects.all(),
}

sitemap_dict = {"sitemaps": {"question": GenericSitemap(info_dict, priority=0.8)}}


urlpatterns = [
    path("list/", views.quiz_list, name="quiz_list"),
    path("<slug:slug>/<int:level>/", views.quiz_detail, name="quiz_detail"),
    path(
        "<slug:slug_quiz>/<int:level_quiz>/<slug:slug_lection>/<int:id_question>/",
        views.question_detail,
        name="question_detail",
    ),
    # htmx
    path("hx/search-quizzes/", views.search_quizzes, name="search_quizzes"),
    path(
        "hx/<slug:slug_quiz>/<int:level_quiz>/<slug:slug_lection>/<int:id_question>/check-answer/",
        views.check_answer,
        name="check_answer",
    ),
    path(
        "hx/<slug:slug_quiz>/<int:level_quiz>/<slug:slug_lection>/<int:id_question>/update-progress-bar/",
        views.update_progress_bar,
        name="update_progress_bar",
    ),
    # htmx - question translation
    path(
        "hx/question/translate/<int:id_question>/<int:id_language>/",
        views.translate_question_text,
        name="quiz_translate_question_text",
    ),
    # sitemaps
    path(
        "questions/sitemap.xml",
        sitemap,
        sitemap_dict,
        name="django.contrib.sitemaps.views.sitemap",
    ),
    # not used, used Bootstrap Bundle JS instead
    path(
        "hx/question/get-translation-modal/<int:id_question>/",
        views.get_question_translation_modal,
        name="quiz_get_translation_modal",
    ),
    path(
        "hx/question/remove-translation-modal/<int:id_question>/",
        views.remove_question_translation_modal,
        name="quiz_remove_translation_modal",
    ),
]

quiz/models.py
from __future__ import annotations

from django.db import models
from django.urls import reverse
from django.utils.text import slugify

QUIZ_LEVEL_CHOICES = (
    (1, "A1"),
    (2, "A2"),
    (3, "B1"),
    (4, "B2"),
    (5, "C1"),
    (6, "C2"),
)

QUESTION_TYPE_CHOICES = (
    (1, "1: One text input"),
    (2, "2: Two text input"),
    (5, "5: One choice selection"),
    (6, "6: Multiple choice selection"),
)


class Quiz(models.Model):
    name = models.CharField(max_length=64)
    level = models.IntegerField(default=5, choices=QUIZ_LEVEL_CHOICES)
    slug = models.SlugField(blank=True, unique=True)
    image_url = models.URLField(max_length=200, blank=True, null=True)
    image_credits_url = models.URLField(max_length=200, null=True)
    views = models.PositiveIntegerField(default=0)

    def get_detail_url(self):
        return reverse("quiz_detail", kwargs={"slug": self.slug, "level": self.level})

    def get_absolute_url(self):
        return self.get_detail_url()

    def get_list_url(self):
        return reverse("quiz_list")

    def add_view(self):
        self.views += 1
        self.save()

    def __str__(self):
        return f"{self.get_level_display()} - {self.name}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ("-views",)


class Lection(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    slug = models.SlugField(blank=True)
    views = models.PositiveIntegerField(default=0)

    def get_first_question(self):
        return self.question_set.all().first()

    def get_absolute_url(self):
        return self.get_first_question().get_detail_url()

    def add_view(self):
        self.views += 1
        self.save()

    def __str__(self):
        return f"{self.name} ({self.quiz.name})"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ("name",)


class Question(models.Model):
    lection = models.ForeignKey(Lection, on_delete=models.CASCADE)
    text_one = models.CharField(max_length=200, null=True, blank=True)
    text_two = models.CharField(max_length=200, null=True, blank=True)
    text_three = models.CharField(max_length=200, null=True, blank=True)
    type = models.PositiveSmallIntegerField(default=1, choices=QUESTION_TYPE_CHOICES)
    explanation = models.CharField(max_length=250, blank=True, null=True)
    promoted = models.BooleanField(default=False)

    @property
    def full_text(self):
        text = ""
        if self.type == 1:
            text += f"{self.text_one} ____ {self.text_two}"
            if self.text_three:
                text += f" ____ {self.text_three}"

        if self.type == 5:
            text += f"{self.text_one}"
            if self.text_two:
                text += f"\n {self.text_two}"
            if self.text_three:
                text += f"\n {self.text_three}"
        return text

    def get_detail_url(self):
        return reverse(
            "question_detail",
            kwargs={
                "slug_quiz": self.lection.quiz.slug,
                "level_quiz": self.lection.quiz.level,
                "slug_lection": self.lection.slug,
                "id_question": self.id,
            },
        )

    def get_absolute_url(self):
        return self.get_detail_url()

    def check_answer_url(self):
        return reverse(
            "check_answer",
            kwargs={
                "slug_quiz": self.lection.quiz.slug,
                "level_quiz": self.lection.quiz.level,
                "slug_lection": self.lection.slug,
                "id_question": self.id,
            },
        )

    def update_progress_bar_url(self):
        return reverse(
            "update_progress_bar",
            kwargs={
                "slug_quiz": self.lection.quiz.slug,
                "level_quiz": self.lection.quiz.level,
                "slug_lection": self.lection.slug,
                "id_question": self.id,
            },
        )

    def get_translation_modal_url(self):  # not used, used Bootstrap Bundle JS instead
        return reverse("quiz_get_translation_modal", kwargs={"id_question": self.id})

    def remove_translation_modal_url(
        self,
    ):  # not used, used Bootstrap Bundle JS instead
        return reverse("quiz_remove_translation_modal", kwargs={"id_question": self.id})

    def is_first(self):
        return self.__class__.objects.filter(lection=self.lection).first() == self

    def is_last(self):
        return self.__class__.objects.filter(lection=self.lection).last() == self

    def previous_object(self):
        return (
            self.__class__.objects.filter(id__lt=self.id, lection=self.lection)
            .order_by("id")
            .last()
        )

    def next_object(self):
        return (
            self.__class__.objects.filter(id__gt=self.id, lection=self.lection)
            .order_by("id")
            .first()
        )

    def __str__(self):
        return f"{self.lection.quiz.name} - {self.lection.name} - {self.text_one}"

    class Meta:
        ordering = ("id",)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class DeeplLanguage(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=5)
    supports_formality = models.BooleanField(default=False)
    views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["-views"]

    def __str__(self) -> str:
        return self.name

    def add_view(self):
        self.views += 1
        self.save()


class TranslatedQuestion(models.Model):
    language = models.ForeignKey(DeeplLanguage, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    original_text = models.CharField(max_length=650)
    translated_text = models.CharField(max_length=650)

    created = models.DateField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self) -> str:
        return self.original_text

templates/quiz/partials/check_or_next_button.html
<div class="fixed-bottom container" hx-boost="true">
    <div class="row">
        <div class="col-md-8 offset-md-2 mb-2">
            {% if not question.is_last %}
                <a  class="btn btn-lg btn-dark w-100 h-100 "
                    href="{{ question.next_object.get_detail_url }}">Next <i class="bi bi-arrow-right"></i></a>
            {% else %}
                <a  class="btn btn-lg btn-success w-100 h-100 "
                    href="{{ question.lection.quiz.get_detail_url }}"><i class="bi bi-check-lg"></i> Done</a>
            {% endif %}
        </div>
    </div>
</div>

templates/quiz/partials/progress_bar.html
<div class="progress h-100 ">
    <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" role="progressbar" style="width: {{ progress_percentage }}%">
    </div>
</div>

templates/quiz/partials/question_correct.html
<div class="container mt-3">
    <div class="row">
        <div class="col-md-8 offset-md-2">

            {% if question.type == 1 %}
                <p class="fs-2 text-center py-1">
                    {% if question.text_one %} {{ question.text_one }} {% endif %}
                    <strong class="text-success" ><u>{{ correct_answer_one }}</u></strong>
                    {% if question.text_two %} {{ question.text_two }} {% endif %}
                </p>

            {% elif question.type == 2 %}
                <p class="fs-2 text-center py-1">
                    {% if question.text_one %} {{ question.text_one }} {% endif %}
                    <strong class="text-success" ><u>{{ correct_answer_one }}</u></strong>
                    {% if question.text_two %} {{ question.text_two }} {% endif %}
                    <strong class="text-success"><u>{{ correct_answer_two }}</u></strong>
                    {% if question.text_three %}{{ question.text_three }} {% endif %}
                </p>

            {% elif question.type == 5 %}
                <p class="fs-2 text-center py-1">{{ question.text_one }}</p>
                {% if question.text_two %}<p class="fs-2 text-center py-1">{{ question.text_two }}</p>{% endif %}
                {% if question.text_three %}<p class="fs-2 text-center py-1">{{ question.text_three }}</p>{% endif %}

            {% endif %}
        </div>
    </div>
</div>

<div class="container mt-3">
    <div class="col-md-8 offset-md-2">
        {% if question.type == 5 %}
            {% for answer in question.answer_set.all %}
                <p class="py-1">
                    {% if answer.correct %}
                        <button type="button" name="button" class="btn btn-lg btn-success border-0 w-100" disabled>{{answer.name}}</button>
                    {% else %}
                        <button type="button" name="button" class="btn btn-lg btn-outline-dark border-0 w-100" disabled>{{answer.name}}</button>
                    {% endif %}
                </p>
            {% endfor %}
        {% endif %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong> {{ correct_message }} </strong>
            {% if question.explanation %}<p>{{ question.explanation }}</p>{% endif %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>


{% include "quiz/partials/check_or_next_button.html" %}

templates/quiz/partials/question_incorrect.html
<div class="container mt-3">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% if question.type == 1 %}
                <p class="fs-2 text-center py-1">
                    {% if question.text_one %} {{ question.text_one }} {% endif %}
                    <strong {% if answer_one_is_correct %}class="text-success"{% else %}class="text-danger"{% endif %} ><u>{{ correct_answer_one }}</u></strong>
                    {% if question.text_two %} {{ question.text_two }} {% endif %}
                </p>

            {% elif question.type == 2 %}
                <p class="fs-2 text-center py-1">
                    {% if question.text_one %} {{ question.text_one }} {% endif %}
                    <strong {% if answer_one_is_correct %}class="text-success"{% else %}class="text-danger"{% endif %} ><u>{{ correct_answer_one }}</u></strong>
                    {% if question.text_two %} {{ question.text_two }} {% endif %}
                    <strong {% if answer_two_is_correct %}class="text-success"{% else %}class="text-danger"{% endif %}><u>{{ correct_answer_two }}</u></strong>
                    {% if question.text_three %} {{ question.text_three }} {% endif %}
                </p>

            {% elif question.type == 5 %}
                <p class="fs-2 text-center py-1">{{ question.text_one }}</p>
                {% if question.text_two %}
                    <p class="fs-2 text-center py-1">{{ question.text_two }}</p>
                {% endif %}
                {% if question.text_three %}
                    <p class="fs-2 text-center py-1">{{ question.text_three }}</p>
                {% endif %}

            {% endif %}
        </div>
    </div>
</div>


<div class="container mt-3">
    <div class="col-md-8 offset-md-2">
        {% if question.type == 5 %}
            {% for answer in question.answer_set.all %}
                <p class="py-1">
                    {% if answer.correct %}
                        <button type="button" name="button" class="btn btn-lg btn-success border-0 w-100" disabled>{{answer.name}}</button>
                    {% elif answer == selected_answer %}
                        <button type="button" name="button" class="btn btn-lg btn-danger border-0 w-100" disabled>{{answer.name}}</button>
                    {% else %}
                        <button type="button" name="button" class="btn btn-lg btn-outline-dark border-0 w-100" disabled>{{answer.name}}</button>
                    {% endif %}
                </p>
            {% endfor %}
        {% endif %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong> {{ incorrect_message }} </strong>
            {% if question.explanation %}<p>{{ question.explanation }}</p>{% endif %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>


{% include "quiz/partials/check_or_next_button.html" %}

templates/quiz/partials/question_translated_text.html
<h4 id="translated-text-here" class="text-primary mt-5">{{ translated_text }}</h4>

templates/quiz/partials/quiz_list.html
{% load humanize %}

{% for quiz in quiz_list %}
    <div class="col-sm-12 col-md-6 col-lg-4 mb-5">
        <div class="card" style="background-color: Beige;">
            <img src="{{ quiz.image_url }}" width="400" height="250" class="card-img-top" alt="...">
            <small class="text-muted">Photo by <a class="text-muted" target="_blank" href="{{ quiz.image_credits_url }}">{{ quiz.image_credits_url }}</a> </small>
            <div class="card-body ">
                <p class="text-secondary">Difficulty
                    <span class="text-success float-end">
                        {% if quiz.level > 4 %}<i class="bi bi-circle-fill"></i> <i class="bi bi-circle-fill"></i> <i class="bi bi-circle-fill"></i> {% endif %}
                        {% if quiz.level == 4 %}<i class="bi bi-circle-fill"></i> <i class="bi bi-circle-fill"></i> <i class="bi bi-circle"></i> {% endif %}
                        {% if quiz.level < 4 %}<i class="bi bi-circle-fill"></i> <i class="bi bi-circle"></i> <i class="bi bi-circle"></i> {% endif %}
                    </span>
                </p>
                <p class="text-secondary">Views
                    <span class="text-success float-end"> {{ quiz.views | intcomma }} </span>
                </p>
                <a href="{{ quiz.get_detail_url }}" class="btn btn-lg btn-success w-100 fs-3">{{ quiz.name}}</a>
            </div>
        </div>
    </div>
{% empty %}
    <div class="col-sm-12 col-md-6 col-lg-4 mb-5">
        <p class="text-center text-success">Sorry, we didn't find anything for you <i class="bi bi-emoji-frown"></i></p>
    </div>
{% endfor %}